config/routes.rb
Rails.application.routes.draw do
  resources :comments
  resources :issues
  
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  root 'issues#index'
  
  resources :issues do
    resources :comments
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  
  post '/issues/:id/vote' => "issues#vote", as: :vote
  post '/issues/:id/watch' => "issues#watch", as: :watch
  put '/issues/:id/delete_attachment' => "issues#delete_attachment", as: :delete_attachment
  put '/issues/:id/status' => "issues#update_status", as: :update_status
  delete '/users/sign_out' => "issues#sign_out", as: :sign_out
  
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :issue
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :edit, :update, :destroy]

  # GET /comments
  # GET /comments.json
  def index
    @comments = Comment.all
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
  end

  # GET /comments/new
  def new
    @comment = Comment.new
  end

  # GET /comments/1/edit
  def edit
  end

  # POST /comments
  # POST /comments.json
  def create
    @issue = Issue.find(params[:issue_id])
    @comment = @issue.comments.new(comment_params)
    @comment.user = current_user

    respond_to do |format|
      if @comment.save
        format.html { redirect_to @issue, notice: 'Comment was successfully created.' }
        format.json { render :show, status: :created, location: @comment }
      else
        format.html { render :new }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comments/1
  # PATCH/PUT /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to @comment.issue, notice: 'Comment was successfully updated.' }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @iss_id = @comment.issue_id
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to issue_path(@iss_id), notice: 'Comment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end
    
    def find_post
      @issue = Issue.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.fetch(:comment, {}).permit(:issue_id, :body, :user_id)
    end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.html.erb
<%
noRegistrado = false

if User.exists?(comment.user.id)
  userName = User.find(comment.user.id).name
else
  userName = comment.user.id.to_s
  noRegistrado = true
end


iniciales = userName.strip.split /\s+/

avatarName = 'X'

if iniciales.length == 1 && !noRegistrado
  ini1 = iniciales[0]
  avatarName = ini1[0,1].upcase
end
if iniciales.length > 1  && !noRegistrado
  ini1 = iniciales[0]
  ini2 = iniciales[1]
  avatarName = ini1[0,1].upcase + ini2[0,1].upcase
end

backColours = ['Gold', 'Limegreen', 'LightBlue', 'Bisque', 'Pink', 'Tomato', 'Orangered', 
'Palegoldenrod', 'Palegreen', 'Mistyrose']
numIdColor = comment.user.id.to_i % 10
backColour = backColours[numIdColor]

%>

<div class="comment">
  <div class="ownerUserComment">
    <div class="avatar" style="background:<%= backColour %>;"><%= avatarName %></div>
    <p class="nameComment"><%= comment.user.name %></p>
  </div>  
  
  <div class="commentContent">
    <p><%= comment.body  %></p>
    <% if not comment.system %>
      <% if comment.user == current_user %>
        <%= link_to 'Edit', edit_issue_comment_path(comment.issue_id, comment.id, comment.body) %> 
        <span class='punto'>·</span>
        <%= link_to 'Delete', comment, method: :delete, data: {confirm: 'Are you sure?' } %>
        <span class='punto'>·</span>
        <%= time_ago_in_words(comment.created_at) + ' ago'%>
        <br><br>
      <%end%>
    <% else %>
      <span class='punto'>·</span>
      <%= time_ago_in_words(comment.created_at) + ' ago'%>
      <br><br>
    <% end %>
  </div>
</div>

app/views/comments/_form.html.erb
<%= form_with(model: comment, local: true) do |form| %>
  
  <%= form.label :body %>
  <div class="field ">
    <%= form.text_area :body, class:"min_size" %>
  </div>

  <div class="actions left">
    <%=  form.submit class:"btn btn-primary separator" %>
    <%= link_to 'Cancel', @comment.issue, class:"cancel"%>
  </div>
  
<% end %>

app/views/comments/edit.html.erb
<h1>Edit Comment</h1>

<%= render 'form', comment: @comment %>

app/views/comments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Comments</h1>

<table>
  <thead>
    <tr>
      <th>Issue</th>
      <th>Body</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.issue_id %></td>
        <td><%= comment.body %></td>
        <td><%= comment.user_id %></td>
        <td><%= link_to 'Show', comment %></td>
        <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
        <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Comment', new_comment_path %>

app/views/comments/new.html.erb
<h1>New Comment</h1>

<%= render 'form', comment: @comment %>

<%= link_to 'Back', comments_path %>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Issue:</strong>
  <%= @comment.issue_id %>
</p>

<p>
  <strong>Body:</strong>
  <%= @comment.body %>
</p>

<p>
  <strong>User:</strong>
  <%= @comment.user_id %>
</p>

<%= link_to 'Edit', edit_issue_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>