config/routes.rb
Rails.application.routes.draw do
  resources :comments
  resources :issues
  
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  root 'issues#index'
  
  resources :issues do
    resources :comments
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  
  post '/issues/:id/vote' => "issues#vote", as: :vote
  post '/issues/:id/watch' => "issues#watch", as: :watch
  put '/issues/:id/delete_attachment' => "issues#delete_attachment", as: :delete_attachment
  put '/issues/:id/status' => "issues#update_status", as: :update_status
  delete '/users/sign_out' => "issues#sign_out", as: :sign_out
  
end

app/models/issue.rb
class Issue < ApplicationRecord
  has_many_attached :attachments
  default_scope { order(created_at: :desc)}
  belongs_to :user

  has_many :comments
  has_many :votes, dependent: :destroy
  has_many :watchers, dependent: :destroy
  
  validates :title, presence: true
  validates :issueType, presence: true
  validates :priority, presence: true
  validates :status, presence: true
  
  def self.status
        ["New", "Open", "On hold", "Resolved", "Duplicate", "Invalid", "Won't fix", "Closed"]
  end
end

app/controllers/issues_controller.rb
class IssuesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_issue, only: [:show, :edit, :update, :destroy]
  
$actualOrder = "asc"
  
  # GET /issues
  # GET /issues.json
  def index
    @issues = Issue.all
    if params.has_key?(:typeOptions)
      @issues = Issue.where(issueType: params[:typeOptions])
    end
      
      
    if params.has_key?(:priorityOptions)
      @issues = Issue.where(priority: params[:priorityOptions])
    end
    
    
    if params.has_key?(:statusOptions)
      if params[:statusOptions] == "New&open"
        @issues = Issue.where(status: ["Open", "New"])
      else
        @issues = Issue.where(status: params[:statusOptions])
      end
    end
    
    if params.has_key?(:idActualUser)
      userName = User.find(params[:idActualUser]).name
      @issues = Issue.where(assignee: userName)
    end
    
    if params.has_key?(:watcher)
      if User.exists?(id: params[:watcher])
        @issues = Issue.joins(:watchers).where(watchers: {user_id: params[:watcher]})
      end
    end
    
    
    if params.has_key?(:assignee)
      if !params[:assignee].nil?
        @issues = Issue.where(assignee: params[:assignee])
      end
    end
    
    
    if params.has_key?(:OrderBy)
      if params[:OrderBy] == "title"
        if $actualOrder == "asc"
          @issues = Issue.reorder(:title)
          $actualOrder = "desc";
        else 
          @issues = Issue.reorder(title: :desc)
          $actualOrder = "asc";
        end
      end
      
      if params[:OrderBy] == "type"
        if $actualOrder == "asc"
          @issues = Issue.reorder(:issueType)
          $actualOrder = "desc";
        else 
          @issues = Issue.reorder(issueType: :desc)
          $actualOrder = "asc";
        end
      end
      
      if params[:OrderBy] == "priority"
        if $actualOrder == "asc"
          @issues = Issue.reorder(:priority)
          $actualOrder = "desc";
        else 
          @issues = Issue.reorder(priority: :desc)
          $actualOrder = "asc";
        end
      end
      
      if params[:OrderBy] == "status"
        if $actualOrder == "asc"
          @issues = Issue.reorder(:status)
          $actualOrder = "desc";
        else 
          @issues = Issue.reorder(status: :desc)
          $actualOrder = "asc";
        end
      end
      
      if params[:OrderBy] == "votes"
        if $actualOrder == "asc"
          @issues = Issue.reorder(:num_votes)
          $actualOrder = "desc";
        else 
          @issues = Issue.reorder(num_votes: :desc)
          $actualOrder = "asc";
        end
      end
      
      if params[:OrderBy] == "assignee"
        if $actualOrder == "asc"
          @issues = Issue.reorder(:assignee)
          $actualOrder = "desc";
        else 
          @issues = Issue.reorder(assignee: :desc)
          $actualOrder = "asc";
        end
      end
      
      if params[:OrderBy] == "created"
        if $actualOrder == "asc"
          @issues = Issue.reorder(:created_at)
          $actualOrder = "desc";
        else 
          @issues = Issue.reorder(created_at: :desc)
          $actualOrder = "asc";
        end
      end
      
      if params[:OrderBy] == "updated"
        if $actualOrder == "asc"
          @issues = Issue.reorder(:updated_at)
          $actualOrder = "desc";
        else 
          @issues = Issue.reorder(updated_at: :desc)
          $actualOrder = "asc";
        end
      end
      
    end
  end

  # GET /issues/1
  # GET /issues/1.json
  def show
    
    @comments = Comment.where(issue_id: @issue).order("created_at DESC")
  end

  # GET /issues/new
  def new
    @issue = Issue.new
  end

  # GET /issues/1/edit
  def edit
  end
  
  
  
  # POST /issues/issue_id/vote
  def vote
    respond_to do |format|
      @issue_voted = Issue.find(params[:id])
      if !Vote.exists?(:issue_id => @issue_voted.id, :user_id => current_user.id)
        @vote = Vote.new
        @vote.user_id = current_user.id
        @vote.issue_id = @issue_voted.id
        @vote.save
        @issue_voted.increment!("num_votes")
      else
        @vote = Vote.where(issue_id: params[:id], user_id: current_user.id).take
        @vote.destroy
        @issue_voted.decrement!("num_votes")
      end
      format.html {redirect_to @issue_voted}
      format.json {render json: @issue_voted, status: :ok}
    end
  end
  
  # POST /issues/issue_id/watch
  def watch
    respond_to do |format|
      @issue_watched = Issue.find(params[:id])
      if !Watcher.exists?(:issue_id => @issue_watched.id, :user_id => current_user.id)
        @watcher = Watcher.new
        @watcher.user_id = current_user.id
        @watcher.issue_id = @issue_watched.id
        @watcher.save
      else
        @watcher = Watcher.where(issue_id: params[:id], user_id: current_user.id).take
        @watcher.destroy
      end
      if params[:currentView] == "ind"
        format.html {redirect_to issues_url}
      else
        format.html {redirect_to @issue_watched}
      end
      format.json {render json: @issue_watched, status: :ok}
    end
  end
  
  # PUT /issues/attach_id/delete_attachment
  def delete_attachment
    #@fichero = ActiveStorage::Blob.find_signed(params[:id])
    #@fichero.purge
    @issue_actual = Issue.find(params[:id])
    @issue_actual.attachments.purge
    redirect_to @issue_actual
  end
  
  # DELETE /issues/sign_out
  def sign_out
    reset_session
    session.clear
    redirect_to issues_url
  end

  # POST /issues
  # POST /issues.json
  def create
    @issue = Issue.new(issue_params)
    @issue.num_votes = 0
    @issue.user_id = current_user.id
    @issue.status = "New"

    respond_to do |format|
      if @issue.save
        format.html { redirect_to @issue }
        format.json { render :show, status: :created, location: @issue }
      else
        format.html { render :new }
        format.json { render json: @issue.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /issues/1
  # PATCH/PUT /issues/1.json
  def update
    @priority = @issue.priority
    @type = @issue.issueType
    @title = @issue.title
    @desc = @issue.description
    @att = @issue.attachments
    @status = @issue.status

    respond_to do |format|
      if @issue.update(issue_params)
        if @issue.priority != @priority || @issue.title != @title || @issue.issueType != @type || @issue.description != @desc || @att.length != @issue.attachments.length
          @body = ''
          
          if @issue.priority != @priority
            @body = @body + "\n" + "marked as " + @issue.priority
          end
          if @issue.title != @title
            @body = @body + "\n" + "changed title to " + @issue.title
          end
          if @issue.issueType != @type
            @body = @body + "\n" + 'marked as ' + @issue.issueType
          end
          if @issue.description != @desc
            @body = @body + "\n" + 'edited description'
          end
          
          if @att.length != @issue.attachments.length
            
            if @att.length < @issue.attachments.length
              @esta = false
              @diff = @issue.attachments.length - @att.length
              (0...@issue.attachments.count).each do |attach|
                @name = @issue.attachments[attach].filename
                (0...@att.count).each do |at|
                  if @att[at].filename == @name
                    @esta = true
                    
                  end
                end
                if not @esta 
                  @body = @body + "\n" + 'attached file ' + @name
                else
                  @esta = false
                end
              end
            end
            
          end
              
          @comment = set_issue.comments.build(body: @body)
          @comment.user = current_user
          @comment.system = true
          @comment.save
        end
        
        format.html { redirect_to @issue, notice: 'Issue was successfully updated.' }
        format.json { render :show, status: :ok, location: @issue }
      else
        format.html { render :edit }
        format.json { render json: @issue.errors, status: :unprocessable_entity }
      end
    end
  end
  
  def update_status
    respond_to do |format|
      @issue_to_update = Issue.find(params[:id])
      @status = @issue_to_update.status
      @issue_to_update.update_attribute("status", params[:status])
      if @status != @issue_to_update.status
        @comment = @issue_to_update.comments.build(body: 'marked as ' + @issue_to_update.status)
        @comment.user = current_user
        @comment.system = true
        @comment.save
      end
      format.html { redirect_to @issue_to_update }
      format.json { render json: @issue_to_update, status: :ok }
    end
  end
    
  # DELETE /issues/1
  # DELETE /issues/1.json
  def destroy
    @issue.destroy
    respond_to do |format|
      format.html { redirect_to issues_url}
      format.json { head :no_content }
    end
  end
  
  
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_issue
      @issue = Issue.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def issue_params
      params.require(:issue).permit(:title, :assignee, :issueType, :priority, :user_id, :description,  attachments: [])
    end
end

app/helpers/issues_helper.rb
module IssuesHelper
end

app/views/issues/_form.html.erb
<%= form_with(model: issue, local: true) do |form| %>
  <% if issue.errors.any? %>
    <div class="alert alert-danger errors">
      <ul>
        <% issue.errors.full_messages.each do |error| %>
          <li><%= error %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :title , class:"nonegrita lado"%>
    <%= form.text_field :title, class:"form-control titleHover" %>
  </div>
  
  <div class="form-group">
    <%= form.label :description, class:"nonegrita" %>
    <%= form.text_area(:description, size: '50x10', class:"form-control") %>
  </div>

  <div class="form-group">
    <%= form.label :assignee , class:"nonegrita"%>
   
    <%= form.text_field :assignee, class:"form-control" %>
  </div>
  
  <div class="form-group">
    <%= form.label "Kind", class: 'control-label' , class:"nonegrita"%>
    <div class="controls">
      <%= form.select(:issueType, options_for_select([['bug','bug'],['enhancement','enhancement'],['proposal','proposal'],['task','task']]))%>
    </div>
  </div>
  
  <div class="form-group">
    <%= form.label "Priority", class: 'control-label', class:"nonegrita lado" %>
    <div class="controls">
      <%= form.select(:priority, options_for_select([['trivial','trivial'],['minor','minor'],['major','major'],['critical','critical'],['blocker','blocker']]))%>
    </div>
  </div>
  

  <div class="form-group">
     <div class="field">
      <%= form.label :attachments, class:"nonegrita " %>
      <%= form.file_field :attachments, multiple: true %>
    </div>
  </div>
  
  <div class="actions dreta">
    <%=  form.submit class:"btn btn-primary separator" %>
    <%= link_to 'Cancel', issues_path, class:"cancel"%>
  </div>
<% end %>

app/views/issues/edit.html.erb
<div class="title-container">
  <h1>Issues</h1>
</div>
<h2>Edit Issue</h2>


<%= render 'form', issue: @issue %>


<%= link_to 'Show', @issue %> |

<%= link_to 'Back', issue_path %>

app/views/issues/index.html.erb
<p id="notice"><%= notice %></p>

<%= link_to raw("<button class='btn btn-default'>Logout</button>"), 
    destroy_user_session_path, 
    method: :delete %>

<div class="title-container">
  <h1 >Issues</h1>
  <%= link_to 'Create Issue', new_issue_path, class:"btn btn-default"%>
</div>


<div class="linia_completa">
  <div class="filter_title">Filter by:</div>
  <div class="meitat_filtres">
       <div id="All">
        <a href="/issues"   class="filter_derecha btn btn-default ">All</a>
      </div>
    
      <div id="Open">
        <a ><%= link_to "Open", issues_url(statusOptions: "New&open") ,class:"filter_derecha btn btn-default quitar_subrayado" %> </a>
      </div>
      
      <div id="My issues">
        <a><%= link_to "My issues", issues_url(idActualUser: current_user.id) ,class:"filter_derecha btn btn-default quitar_subrayado"%> </a>
      </div>

      <div id="Watching" >
        <a><%= link_to "Watching", issues_url(watcher: current_user.id) ,class:"filter_derecha btn btn-default quitar_subrayado"%> </a>
      </div>
  </div>
</div>

<div class="linia_completa_issues"><h2 class="textSize">Issues (1-<%= @issues.size %> of <%= @issues.size %>)</h2> </div>

<p id="issues-filter-criteria">
  <% if request.query_parameters[:typeOptions] %>
    <b>type:</b> "<%= request.query_parameters[:typeOptions] %>"
  <% end %>
  
  <% if request.query_parameters[:priorityOptions] %>
    <b>priority:</b> "<%= request.query_parameters[:priorityOptions] %>"
  <% end %>
  
  <% if request.query_parameters[:statusOptions] %>
    <b>status:</b> "<%= request.query_parameters[:statusOptions] %>"
  <% end %>
  
  <% if request.query_parameters[:assignee] %>
    <b>assignee:</b> "<%= request.query_parameters[:assignee] %>"
  <% end %>
  
</p>

<div class="issues">
  <table>
      <tbody>
        <table class="table table-striped table-hover ">
          <thead>
            <tr>
              <th class="tileVariables "><%= link_to "Title", issues_url(OrderBy: "title"),class:"quitar_subrayado" %></th>
              <th class="tileVariables"><%= link_to "T", issues_url(OrderBy: "type") ,class:"quitar_subrayado"%></th>
              <th class="tileVariables"><%= link_to "P", issues_url(OrderBy: "priority") ,class:"quitar_subrayado"%></th>
              <th class="tileVariables"><%= link_to "Status", issues_url(OrderBy: "status") ,class:"quitar_subrayado"%></th>
              <th class="tileVariables"><%= link_to "Votes", issues_url(OrderBy: "votes") ,class:"quitar_subrayado"%></th>
              <th class="tileVariables"><%= link_to "Assignee", issues_url(OrderBy: "assignee"),class:"quitar_subrayado" %></th>
              <th class="tileVariables"><%= link_to "Created", issues_url(OrderBy: "created") ,class:"quitar_subrayado"%></th>
              <th class="tileVariables"><%= link_to "Updated", issues_url(OrderBy: "updated"),class:"quitar_subrayado" %></th>
            </tr>
          </thead>
          <% @issues.each do |issue| %>
              <div class="issue">
                <tr>
                  <td class="col"><%= link_to issue.title, issue,class:"quitar_subrayado" %></td>
                  <td class="col"><%= link_to issue.issueType, issues_url(typeOptions: issue.issueType),class:"quitar_subrayado" %></td>
                  <td class="col"><%= link_to issue.priority, issues_url(priorityOptions: issue.priority),class:"quitar_subrayado" %></td>
                  <td class="col"><%= link_to issue.status, issues_url(statusOptions: issue.status) ,class:"quitar_subrayado"%></td>
                  <td class="col"><%= issue.num_votes %></td>
                  
                  <% if !issue.assignee.nil? && !issue.assignee.empty? %>
                    <td class="col">
                      <%
                      noRegistrado = false
                      if User.exists?(issue.assignee)
                        userName = User.find(issue.assignee).name
                      else
                        userName = issue.assignee
                        noRegistrado = true
                      end
                      
                      iniciales = userName.strip.split /\s+/
                      avatarName = 'X'
                      
                      if iniciales.length == 1 && !noRegistrado
                        ini1 = iniciales[0]
                        avatarName = ini1[0,1].upcase
                      end
                      if iniciales.length > 1  && !noRegistrado
                        ini1 = iniciales[0]
                        ini2 = iniciales[1]
                        avatarName = ini1[0,1].upcase + ini2[0,1].upcase
                      end
                      
                      backColours = ['Gold', 'Limegreen', 'LightBlue', 'Bisque', 'Pink', 'Tomato', 'Orangered', 
                      'Palegoldenrod', 'Palegreen', 'Mistyrose']
                      numIdColor = issue.assignee.to_i % 10
                      backColour = backColours[numIdColor]
                      %>
                      <div id='indexAssigne'>
                        <div class="avatar" style="background:<%= backColour %>;"><%= avatarName %></div>
                        <%= link_to userName, issues_url(assignee: issue.assignee), class: "assigneLink" %>
                      </div>
                    </td>

                  <% else %>
                  <td></td>
                  <% end %>
                  <td class="col"><%= issue.created_at %></td>
                  <td class="col"><%= issue.updated_at %></td>
                  <td>
                  <% if  !Watcher.exists?(:issue_id => issue.id, :user_id => current_user.id) %>
                  <%= link_to 'Watch', watch_url(id: issue.id, currentView: "ind"), method: :post,class:"quitar_subrayado" %>
                  <% else %>
                  <%= link_to 'UnWatch', watch_url(id: issue.id, currentView: "ind"), method: :post ,class:"quitar_subrayado"%>
                  <% end %>
                  </td>
                  <td class="col"><%= link_to 'Destroy', issue, method: :delete, data: { confirm: 'Are you sure?' } ,class:"quitar_subrayado"%></td>
                </tr>
              </div>
          <% end %>
        </table>
      </tbody>
  </table>
</div>

<br>

app/views/issues/new.html.erb
<div class="title-container">
  <h1>Issues</h1>
</div>

<h2 class="issue">Create issue</h2>

<%= render 'form', issue: @issue %>

app/views/issues/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Issues', issues_path ,class:"btn btn-default separacion-issues" %>

<div class="title-container separacion-title">
  <h1 class="separacion-title"><%= @issue.title %></h1>
</div>


 <div>
   
   
  <div class="panel-body izquierda-body">
    <p>
      <%= @issue.user_id %>
      created an issue <%= @issue.created_at %>
      <div><%= @issue.description %></div>
    </p>
    
   
  <div>
    <% 
    i = 0
    (0...@issue.attachments.count).each do |attach| %>
      <div>
        <%= link_to raw("<img src='https://image.flaticon.com/icons/png/512/252/252006.png', width='100'>"), 
        @issue.attachments[attach], 
        download: '', 
        class: "no_link" %>
        <p> <%=  @issue.attachments[attach].filename %> </p>
      </div>
      
    <%
    i = i + 1
    end 
    %>
    
    <%= 
    if i > 0
      # Al ir al controller e intentar encontrar el elemento segun el id da error
      link_to raw("Remove attachments <img src='http://icons.iconarchive.com/icons/danieledesantis/playstation-flat/256/playstation-cross-black-and-white-icon.png', width='20'>"),
        delete_attachment_url(@issue.id),
        method: :put,
        data: { confirm: 'Are you sure you want to delete this attachment?' },
        multipart: true
    end
    %>
  
  <hr class="linia_gruesa ">

  <h3 class="comments_title">Comments (<%= @issue.comments.count %>)</h3>
  <div id="comments">
    <%= render :partial => @issue.comments %>
  </div>
  <div class="submit-bottom">
    
        <%= simple_form_for [@issue, Comment.new] do |f| %>
        <div class="field campo-comment"">
          <%= f.text_area :body, class: "form-control" %>
        </div>
        <br>
        <div class: "add-coment-submit> <%= f.submit "Add Comment", class: "btn btn-primary add-coment-submit" %> </div>
      <% end %>
  </div>
  </div>
  
</div>

<div class="form-group derecha_botones derecha-body">
    <div class="col-sm-11 col-sm-offset-1 espacio derecha_create derecha-todo">
      <%= link_to 'Create Issue', new_issue_path ,class:"btn btn-default" %>
    </div>
    
    <div class="col-sm-11 col-sm-offset-1 editIssuesWork derecha-todo">
      <div class="dropdownbloque">
        <button class="btn btn-default dropdown-toggle"  type="button" data-toggle="dropdown" >Workflow</button>
          <div class="dropdown-content">
            <% Issue.status.each do |status| %>
                <% if status != @issue.status %>
                
                <div><a<%= content_tag(:li, link_to(status, update_status_url(id: @issue.id, status: status), method: :put)) %></div></a>
                <% end %>
            <% end %>
          </div>
      </div>
      <%= link_to 'Edit', edit_issue_path(@issue), class:"btn btn-default" %>
    </div>
    
    <div class="panel panel-default info">
      <p>
        <strong >Assignee</strong>
        <%= @issue.assignee %>
      </p>
    
      
      <p>
        <strong>Type</strong>
        <%= link_to @issue.issueType, issues_url(typeOptions: @issue.issueType),class:"quitar_subrayado" %>
      </p>
      <p>
        <strong>Priority</strong>
        <%= link_to @issue.priority, issues_url(priorityOptions: @issue.priority),class:"quitar_subrayado" %>
      </p>
      <p>
        <strong>Status</strong>
        <%= link_to @issue.status, issues_url(statusOptions: @issue.status) ,class:"quitar_subrayado"%>
      </p>
    
      <p>
      <strong>Votes</strong>
        <%= @issue.num_votes %>
        <% if !Vote.exists?(:issue_id => @issue.id, :user_id => current_user.id) %>
          <%= link_to "Vote this issue", vote_url(id: @issue.id), method: :post , class:"quitar_subrayado"%>
        <% else %>
          <%= link_to "Unvote this issue", vote_url(id: @issue.id), method: :post , class:"quitar_subrayado"%>
        <% end %>
      </p>
    
    <p>
      <strong>Watchers</strong>
        <% if !Watcher.exists?(:issue_id => @issue.id, :user_id => current_user.id) %>
          <%= link_to "Watch this issue", watch_url(id: @issue.id, currentView: "iss"), method: :post , class:"quitar_subrayado"%>
        <% else %>
          <%= link_to "Unwatch this issue", watch_url(id: @issue.id, currentView: "iss"), method: :post, class:"quitar_subrayado" %>
        <% end %>
    </p>
  
</div>